 const ActionTypes = {
    CHALLENGE : 'CHALLENGE',
    LOGIN : 'LOGIN',
    CHANGETHEME : 'CHANGETHEME',
    DRAWEROPENANDCLOSE : 'DRAWEROPENANDCLOSE',
    ADDRESSSAVE : 'ADDRESSSAVE',
    WAIGHTUNITSET : 'WAIGHTUNITSET',
    SETUSERLOCATION : 'SETUSERLOCATION',
}
export default ActionTypes;
